[file:bin/get_git_sources.py]
source=git:localmirrors:MetOffice/SimSys_Scripts.git::github_scripts/get_git_sources.py::main

[file:bin/merge_sources.py]
source=git:localmirrors:MetOffice/SimSys_Scripts.git::github_scripts/merge_sources.py::main

[file:bin/tweak_iodef]
mode=auto
source=git:localmirrors:MetOffice/lfric_core.git::bin/tweak_iodef::main

[template variables]
BUILD_LFRIC=true
CASE_SETUP='shallow-hot-jupiter'
COMPILER='cce'
EXPT_DT=1200
EXPT_RESUB='P10D'
EXPT_RUNLEN='P1200D'
EXPT_START='20000101T0000Z'
HOUSEKEEPING=true
LFRIC_CPU='PT30M'
LFRIC_LEVS='l32_3300km'
LFRIC_RES='C48_MG'
MIRROR_LOC="localmirrors:"
MO_EX_HOST='ex'
PHYSICS_CONF='stability'
STRETCH_FACTOR=1.0
TARGET_LONLAT=0.0,0.0
TOTAL_RANKS_REQ=216
USE_MIRRORS=true
USE_TOKENS=true
VN='3.1'
