[namelist:external_forcing]
theta_forcing='shallow_hot_jupiter'

[namelist:extrusion]
domain_height=3.29689E6
number_of_layers=32
planet_radius=1.0E8

[namelist:formulation]
use_physics=.true.

[namelist:idealised]
test='isot_atm'

[namelist:initial_temperature]
!!profile_data=300.0,300.0
!!profile_heights=0.0,10.0e3
!!profile_size=2
theta_surf=1800.0

[namelist:planet]
cp=13226.5
gravity=8.0
omega=2.1E-5
p_zero=1.0E5
rd=3779.0