#!/usr/bin/env bash
# gen-modulefile.sh — write the per-variant Lmod modulefile for LFRIC_STACK.
#
# This replaces the old env-runtime-<variant>.sh shell snippet. The
# environment is loaded with `module load lfric-env/<cray|spack>` (and pixi auto-
# activation does the same via scripts/activate.sh).
#
# To keep the modulefile auditable, the LOGIC (what gets put on PATH/LD_*, the
# conditionals, pushenv composition, ordering) lives in the version-controlled,
# syntax-highlighted scripts/lfric-env.lua. THIS script only resolves the per-
# build paths and emits a flat Lua DATA table; the generated file then runs the
# committed logic with it:
#     local data = { ... }
#     assert(loadfile(".../scripts/lfric-env.lua"))(data)
# (Lmod's sandbox forbids dofile() but allows loadfile() + an argument.)
#
# Called by build.sh after `env view regenerate`, but also runnable on its own to
# regenerate the modulefile without a full rebuild (the env must already be
# concretized + installed; it uses the vendored `spack` CLI from common.sh). For
# the cray variant, run with the Cray PE modules loaded (PrgEnv-gnu + cray-hdf5/
# netcdf) so CRAY_LD_LIBRARY_PATH is populated.
set -uo pipefail

_here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=scripts/common.sh
. "$_here/common.sh"

info() { echo "INFO: $*"; }
warn() { echo "WARN: $*" >&2; }
die()  { echo "ERROR: $*" >&2; exit 1; }

case "$LFRIC_STACK" in
  cray|spack) ;;
  *) die "LFRIC_STACK must be 'cray' or 'spack' (got '$LFRIC_STACK')" ;;
esac

logic="$_here/lfric-env.lua"
view="$SPACK_ENV_DIR/.spack-env/view"
[ -f "$logic" ] || die "missing modulefile logic: $logic"
# Snapshot the committed logic next to the generated modulefiles, under PREFIX,
# and have the modulefile loadfile() THAT copy — not the in-repo original — so
# `module load` stays self-contained: Stage 2 must not depend on the repo path
# (it may have moved/been deleted since the build). Byte-identical to the tracked
# scripts/lfric-env.lua, refreshed every build.
installed_logic="$MODULEFILES_DIR/lfric-env.lua"
[ -d "$view/bin" ] || die "Spack env view missing at $view — build it first: sbatch scripts/build.sbatch (or: pixi run build)"
command -v spack >/dev/null 2>&1 || die "spack CLI not on PATH (common.sh should add it)"

# --- Lua literal helpers (the only quoting this script does) ----------------
lua_q()  { local s=${1:-}; s=${s//\\/\\\\}; s=${s//\"/\\\"}; printf '"%s"' "$s"; }
lua_qn() { if [ -n "${1:-}" ]; then lua_q "$1"; else printf 'nil'; fi; }   # string or nil
lua_list() {                                                               # args -> { "a", "b" } (none -> {})
  local x out=""
  for x in "$@"; do
    [ -n "$out" ] && out+=", "
    out+="$(lua_q "$x")"
  done
  [ -n "$out" ] && printf '{ %s }' "$out" || printf '{}'
}

# --- Resolve the per-build, hash-addressed install prefixes -----------------
shumlib_prefix="$(spack -e "$SPACK_ENV_DIR" location -i shumlib 2>/dev/null || true)"
python_prefix="$(spack -e "$SPACK_ENV_DIR" location -i python 2>/dev/null || true)"
psyclone_prefix="$(spack -e "$SPACK_ENV_DIR" location -i py-psyclone 2>/dev/null || true)"
rose_picker_prefix="$(spack -e "$SPACK_ENV_DIR" location -i rose-picker 2>/dev/null || true)"

shumlib_lib=""
[ -n "$shumlib_prefix" ] && [ -d "$shumlib_prefix/lib" ] && shumlib_lib="$shumlib_prefix/lib"
psyclone_cfg=""
[ -n "$psyclone_prefix" ] && [ -f "$psyclone_prefix/share/psyclone/psyclone.cfg" ] \
  && psyclone_cfg="$psyclone_prefix/share/psyclone/psyclone.cfg"

# The view's python site-packages (usually one; glob in case of a version bump).
pythonpath=()
for _sp in "$view"/lib/python*/site-packages; do
  [ -d "$_sp" ] && pythonpath+=("$_sp")
done

# Cray MPI/IO runtime lib dirs (cray variant only), in final front-to-back order.
cray_libs=()
if [ "$LFRIC_STACK" = cray ]; then
  if [ -n "${CRAY_MPICH_DIR:-}" ]; then
    _OLDIFS=$IFS; IFS=:
    for _d in $CRAY_MPICH_DIR/lib${CRAY_LD_LIBRARY_PATH:+:$CRAY_LD_LIBRARY_PATH}; do
      [ -n "$_d" ] && cray_libs+=("$_d")
    done
    IFS=$_OLDIFS
  else
    warn "CRAY_MPICH_DIR unset — modulefile will lack the Cray MPI lib paths."
    warn "Re-run with the Cray PE modules loaded (PrgEnv-gnu + cray-hdf5/netcdf)."
  fi
fi

pythonpath_lua='{}'; [ ${#pythonpath[@]} -gt 0 ] && pythonpath_lua="$(lua_list "${pythonpath[@]}")"
cray_libs_lua='{}';  [ ${#cray_libs[@]}  -gt 0 ] && cray_libs_lua="$(lua_list "${cray_libs[@]}")"

# --- Emit the data table + a call into the committed logic ------------------
mkdir -p "$(dirname "$MODULEFILE")"
# Place the logic snapshot under PREFIX (shared by both variants) so the emitted
# loadfile() path is repo-independent.
cp -f "$logic" "$installed_logic" || die "failed to snapshot logic to $installed_logic"
info "Writing Lmod modulefile ($MODULEFILE)"
cat > "$MODULEFILE" <<EOF
-- Generated by gen-modulefile.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ'). Do not edit.
-- Per-build path data for the $LFRIC_STACK variant; the logic that consumes it is
-- version-controlled (and audited) in scripts/lfric-env.lua.
local data = {
  variant         = $(lua_q  "$LFRIC_STACK"),
  repo_root       = $(lua_q  "$REPO_ROOT"),
  -- Absolute paths to the (relocated, under-PREFIX) Spack env + its view, so the
  -- modulefile does not derive them from repo_root: Stage 2 stays repo-independent.
  spack_env       = $(lua_q  "$SPACK_ENV_DIR"),
  view            = $(lua_q  "$SPACK_ENV_DIR/.spack-env/view"),
  shumlib         = $(lua_qn "$shumlib_prefix"),
  shumlib_lib     = $(lua_qn "$shumlib_lib"),
  python          = $(lua_qn "$python_prefix"),
  psyclone        = $(lua_qn "$psyclone_prefix"),
  psyclone_cfg    = $(lua_qn "$psyclone_cfg"),
  rose_picker     = $(lua_qn "$rose_picker_prefix"),
  pythonpath      = $pythonpath_lua,
  cray_libs       = $cray_libs_lua,
  target_platform = $(lua_q  "${LFRIC_TARGET_PLATFORM:-meto-spice}"),
  fpp             = $(lua_q  "${FPP:-cpp -traditional-cpp}"),
}
assert(loadfile($(lua_q "$installed_logic")))(data)
EOF

# Mark the unversioned `module load lfric-env` default as the project default
# variant (cray, matching LFRIC_STACK's default). Idempotent; rewritten each build.
cat > "$MODULEFILES_DIR/lfric-env/.modulerc.lua" <<'EOF'
-- Generated by gen-modulefile.sh. Default lfric-env variant = cray (project default).
module_version("lfric-env/cray", "default")
EOF

info "Modulefile written. Load it with:"
info "  module use $MODULEFILES_DIR && module load $MODULE_NAME"
