#!/usr/bin/env bash
# gen-modulefile.sh — write the Lmod modulefile for the active LFRIC_STACK variant.
#
# This replaces the old `working_dir/env-runtime-<variant>.sh` shell snippet: it
# bakes the fully-resolved Spack view + package prefixes into a generated Lua
# modulefile, so the environment is loaded with
#     module use working_dir/modulefiles
#     module load lfric-env/<variant>          # cray | spack
# (and pixi auto-activation does the same via scripts/activate.sh). The two
# variants share the module name "lfric-env", so loading one swaps out the other.
#
# The modulefile is deliberately SELF-CONTAINED — only setenv/prepend_path/
# pushenv, no nested `module load` — so it is fast and works even under /bin/sh
# (how pixi sources the activation hook), and the cray variant carries no runtime
# dependency on the Cray PE modules (their lib dirs are baked into LD_LIBRARY_PATH
# at generate time, exactly as the old snippet did).
#
# Called by build.sh after `env view regenerate`, but also runnable on its own to
# regenerate the modulefile without a full rebuild (the env must already be
# concretized + installed; it uses the vendored `spack` CLI from common.sh).
set -uo pipefail

_here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"
# shellcheck source=scripts/common.sh
. "$_here/common.sh"

info() { echo "INFO: $*"; }
warn() { echo "WARN: $*" >&2; }
die()  { echo "ERROR: $*" >&2; exit 1; }

case "$LFRIC_STACK" in
  cray|spack) ;;
  *) die "LFRIC_STACK must be 'cray' or 'spack' (got '$LFRIC_STACK')" ;;
esac

view="$SPACK_ENV_DIR/.spack-env/view"
[ -d "$view/bin" ] || die "Spack env view missing at $view — run: pixi run build"
command -v spack >/dev/null 2>&1 || die "spack CLI not on PATH (common.sh should add it)"

mkdir -p "$(dirname "$MODULEFILE")"

# Resolve the install prefixes we reference by hash (these change every build).
shumlib_prefix="$(spack -e "$SPACK_ENV_DIR" location -i shumlib 2>/dev/null || true)"
python_prefix="$(spack -e "$SPACK_ENV_DIR" location -i python 2>/dev/null || true)"
psyclone_prefix="$(spack -e "$SPACK_ENV_DIR" location -i py-psyclone 2>/dev/null || true)"
rose_picker_prefix="$(spack -e "$SPACK_ENV_DIR" location -i rose-picker 2>/dev/null || true)"

info "Writing Lmod modulefile ($MODULEFILE)"
{
  echo "-- Generated by gen-modulefile.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ'). Do not edit."
  echo "-- LFRic Apps environment ($ENV_NAME); dependency stack: $LFRIC_STACK."
  echo "whatis(\"Name: $ENV_NAME\")"
  echo "whatis(\"LFRic Apps Spack environment (rose/cylc/psyclone/xios/...), $LFRIC_STACK stack\")"
  echo "help([[Prebuilt LFRic Apps environment ($LFRIC_STACK variant). Puts rose/cylc/"
  echo "psyclone and the Spack view on PATH and sets SHUMLIB_ROOT/SPACK_ENV/... ."
  echo "Built from $REPO_ROOT. Loading the other lfric-env/* version swaps this out.]])"
  echo ""
  # SPACK_ENV makes `spack ...` operate on this environment (the old activate.sh
  # exported it; set it here so a bare `module load lfric-env/<variant>` is enough).
  echo "setenv(\"SPACK_ENV\", \"$SPACK_ENV_DIR\")"
  echo "prepend_path(\"PATH\", \"$view/bin\")"
  # Spack package scripts (e.g. psyclone) carry a shebang to the base python,
  # whose sys.path lacks the env's site-packages. Export the view's site-packages
  # so those scripts can import their own modules.
  for _sp in "$view"/lib/python*/site-packages; do
    [ -d "$_sp" ] && echo "prepend_path(\"PYTHONPATH\", \"$_sp\")"
  done

  if [ -n "$shumlib_prefix" ]; then
    echo "setenv(\"SHUMLIB_ROOT\", \"$shumlib_prefix\")"
    if [ -d "$shumlib_prefix/lib" ]; then
      # LDFLAGS is a space-separated flag string (not a path list): compose it and
      # pushenv so the prior value is restored on unload. LFRic's compile.mk reads
      # it (build-lfric-atm.sh prepends the view's -L/-rpath on top of this).
      echo "local _shumlib_ld = \"-L$shumlib_prefix/lib -Wl,-rpath=$shumlib_prefix/lib\""
      echo "local _ldflags = os.getenv(\"LDFLAGS\")"
      echo "if _ldflags and _ldflags ~= \"\" then"
      echo "  pushenv(\"LDFLAGS\", _ldflags .. \" \" .. _shumlib_ld)"
      echo "else"
      echo "  pushenv(\"LDFLAGS\", _shumlib_ld)"
      echo "end"
      echo "prepend_path(\"LIBRARY_PATH\", \"$shumlib_prefix/lib\")"
      echo "prepend_path(\"LD_LIBRARY_PATH\", \"$shumlib_prefix/lib\")"
    fi
  fi

  # Cray MPI stack (cray-mpich + libfabric + cray-pmi) runtime libraries — cray
  # variant only. They live under /opt/cray (off the default loader path);
  # CRAY_LD_LIBRARY_PATH (set by the PrgEnv-gnu modules build.sh loaded) aggregates
  # them. Bake each dir into LD_LIBRARY_PATH so view binaries that link MPI resolve
  # their .so at runtime. Emitted in reverse so the final order matches the colon
  # list left-to-right (prepend_path pushes to the front). The spack variant links
  # a from-source mpich from the view (RPATH'd by Spack), so nothing is needed.
  if [ "$LFRIC_STACK" = cray ]; then
    if [ -n "${CRAY_MPICH_DIR:-}" ]; then
      _cray_libs="$CRAY_MPICH_DIR/lib${CRAY_LD_LIBRARY_PATH:+:$CRAY_LD_LIBRARY_PATH}"
      _rev=""
      _OLDIFS=$IFS; IFS=:
      for _d in $_cray_libs; do [ -n "$_d" ] && _rev="$_d${_rev:+:$_rev}"; done
      for _d in $_rev; do [ -n "$_d" ] && echo "prepend_path(\"LD_LIBRARY_PATH\", \"$_d\")"; done
      IFS=$_OLDIFS
    else
      warn "CRAY_MPICH_DIR unset — modulefile will lack the Cray MPI lib paths."
      warn "Re-run with the Cray PE modules loaded (PrgEnv-gnu + cray-hdf5/netcdf)."
    fi
  fi

  [ -n "$python_prefix" ]   && echo "prepend_path(\"PATH\", \"$python_prefix/bin\")"
  if [ -n "$psyclone_prefix" ]; then
    echo "prepend_path(\"PATH\", \"$psyclone_prefix/bin\")"
    # The psyclone launcher's shebang python cannot locate its config; point at it.
    [ -f "$psyclone_prefix/share/psyclone/psyclone.cfg" ] \
      && echo "setenv(\"PSYCLONE_CONFIG\", \"$psyclone_prefix/share/psyclone/psyclone.cfg\")"
  fi
  [ -n "$rose_picker_prefix" ] && echo "prepend_path(\"PATH\", \"$rose_picker_prefix/bin\")"

  echo "setenv(\"APPS_ROOT_DIR\", \"$REPO_ROOT/vendor/lfric_apps\")"
  echo "setenv(\"CORE_ROOT_DIR\", \"$REPO_ROOT/vendor/lfric_core\")"
  echo "setenv(\"LFRIC_TARGET_PLATFORM\", \"${LFRIC_TARGET_PLATFORM:-meto-spice}\")"
  echo "setenv(\"FPP\", \"${FPP:-cpp -traditional-cpp}\")"
} > "$MODULEFILE"

# Mark the unversioned `module load lfric-env` default as the project default
# variant (cray, matching LFRIC_STACK's default). Idempotent; rewritten each build.
cat > "$MODULEFILES_DIR/lfric-env/.modulerc.lua" <<'EOF'
-- Generated by gen-modulefile.sh. Default lfric-env variant = cray (project default).
module_version("lfric-env/cray", "default")
EOF

info "Modulefile written. Load it with:"
info "  module use $MODULEFILES_DIR && module load $MODULE_NAME"
