#!/usr/bin/env bash
# Stage the u-dn704 science suite -- LFRic Atm NWP GAL9 NoMG at C12, the Met Office EX
# example workflow -- for Isambard 3. The suite is NOT copied into this repo and NOT
# vendored: it is checked out from its real home, and this repo carries only the diff.
#
# UPSTREAM
#
#     https://code.metoffice.gov.uk/svn/roses-u/d/n/7/0/4/trunk   @ r361458
#     browse: https://code.metoffice.gov.uk/trac/roses-u/browser/d/n/7/0/4/trunk
#
# linked from vendor/lfric_apps/README.md as the "MetOffice EX HPC" example suite. Rose
# workflows live in MOSRS subversion and are staying there -- MetOffice/simulation-systems
# discussion #566 moved the SOURCE extraction to git, explicitly "not where the workflows
# themselves reside" -- so there is no git upstream and nothing to vendor.
#
# Get it the way a Met Office scientist does. `rosie` ships in the environment Stage 1
# builds, and examples/science-suites/site/rose.conf gives it the `u-` prefix map:
#
#     rosie checkout u-dn704            # -> ~/roses/u-dn704 (needs a MOSRS account)
#     svn update -r 361458 ~/roses/u-dn704
#
# Set LFRIC_SUITE_DIR to use a checkout somewhere else. The checkout MUST be at r361458 --
# a mismatch is a hard error, because that is the revision this patch was validated
# against; LFRIC_SUITE_REV overrides the pin for someone re-cutting deliberately.
#
# WHAT THIS DOES: one step. `git apply -p0` of 42-roses-u-u-dn704-isambard3.patch, the
# Isambard 3 port -- 7 files, every hunk carrying an `[isambard3]` comment saying what it
# replaced and why. Because the patch is generated by `svn diff` against the pinned
# revision, the suite's own tools stay the source of truth: `svn diff` in the checkout
# shows exactly our delta, and `svn revert -R .` gives upstream back.
#
# There is deliberately NO `rose app-upgrade` step, unlike the u-dr932 and u-dt000
# stagers. Upstream r361458 (2026-07-17) already moved this suite to
# `meta=lfric-*/vn3.2` and `dependencies.yaml ref: 2026.07.1` -- the same LFRic release
# this environment builds -- so there is no version gap left to close. The assertion
# below is what notices if that stops being true.
#
# Idempotent: re-running is a no-op. This is NOT part of patch-all.sh's stack (it lives
# under patches/suites/, which patch-all's `-maxdepth 1` excludes) -- a suite checked out
# in the user's home is not something an environment build may quietly rewrite.
# examples/science-suites/run-suite.sh runs it.
set -o pipefail
_here="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" && pwd)"

SUITE_ID="u-dn704"
# The revision this patch was cut and validated against. Overridable, but only
# deliberately: see the revision check below.
SUITE_REV="${LFRIC_SUITE_REV:-361458}"
SUITE_URL="https://code.metoffice.gov.uk/svn/roses-u/d/n/7/0/4/trunk"
SUITE_DIR="${LFRIC_SUITE_DIR:-$HOME/roses/$SUITE_ID}"
PATCH_FILE="$_here/42-roses-u-u-dn704-isambard3.patch"
# Must match the LFRic the environment builds (vendor/lfric_apps is pinned at 2026.07.1
# = vn3.2). Bump alongside that pin -- and expect to re-cut the patch when you do.
SUITE_META_VN="${LFRIC_SUITE_META_VN:-vn3.2}"

info() { echo "INFO: $*"; }
warn() { echo "WARN: $*" >&2; }
fail() { echo "ERROR: $*" >&2; }

# --- preconditions ----------------------------------------------------------
if [ ! -d "$SUITE_DIR" ]; then
  warn "no $SUITE_ID checkout at $SUITE_DIR; skipping its site patch."
  warn "  Get it from MOSRS (needs a MOSRS account):"
  warn "    . examples/science-suites/site/activate-env.sh"
  warn "    rosie checkout $SUITE_ID && svn update -r $SUITE_REV $SUITE_DIR"
  warn "  ($SUITE_URL)"
  warn "  or point LFRIC_SUITE_DIR at an existing checkout."
  exit 0
fi
[ -f "$PATCH_FILE" ] || { fail "site patch missing: $PATCH_FILE"; exit 1; }

# --- the revision this patch was cut against --------------------------------
# `svn info` on a working copy is local -- no network, no credentials. A mismatch is a
# HARD error, not a warning: "the patch applies" is not the same claim as "this is the
# revision that was validated", and a patch that happens to apply to a neighbouring
# revision silently gives the user a suite nobody ran. To base on a different revision
# deliberately, say so: LFRIC_SUITE_REV=<rev> (and expect to re-cut the patch).
if command -v svn >/dev/null 2>&1 && [ -d "$SUITE_DIR/.svn" ]; then
  _rev="$(svn info --show-item revision "$SUITE_DIR" 2>/dev/null | tr -d '[:space:]')"
  if [ -n "$_rev" ] && [ "$_rev" != "$SUITE_REV" ]; then
    fail "$SUITE_DIR is at r$_rev; this patch was cut and validated against r$SUITE_REV."
    fail "  Pin the checkout back:"
    fail "    svn update -r $SUITE_REV $SUITE_DIR"
    fail "  or base on r$_rev deliberately (re-cut the patch first -- see"
    fail "  examples/science-suites/$SUITE_ID/README.md, 'Regenerating the site patch'):"
    fail "    LFRIC_SUITE_REV=$_rev ..."
    exit 1
  fi
fi

# --- assert the version gap really is closed --------------------------------
# The whole reason this stager has no `rose app-upgrade` step. If a future upstream
# revision moves the app configs off vn3.2, that step has to come back rather than the
# suite silently building namelists the model will reject.
for _app in lfric_atm mesh; do
  _conf="$SUITE_DIR/app/$_app/rose-app.conf"
  [ -f "$_conf" ] || continue
  if ! grep -q "^meta=.*/${SUITE_META_VN}\$" "$_conf"; then
    fail "app/$_app is not at $SUITE_META_VN: $(grep -m1 '^meta=' "$_conf")"
    fail "  Upstream r$SUITE_REV was already at $SUITE_META_VN, so this checkout is a"
    fail "  different revision, or the environment's LFRic version moved. Either pin the"
    fail "  checkout back, or re-cut the patch WITH a rose app-upgrade step (u-dr932's"
    fail "  stager is the worked example)."
    exit 1
  fi
done

# --- the Isambard 3 site diff -----------------------------------------------
apply_patch() { ( cd "$SUITE_DIR" && git apply -p0 "$@" "$PATCH_FILE" ); }
if apply_patch --reverse --check >/dev/null 2>&1; then
  exit 0   # already applied
fi
if ! apply_patch --check >/dev/null 2>&1; then
  fail "site patch does not apply to $SUITE_DIR."
  fail "  Most likely the checkout is not at r$SUITE_REV, or it has local edits."
  fail "    svn status $SUITE_DIR        # local edits?"
  fail "    svn revert -R $SUITE_DIR     # discard them and start clean"
  exit 1
fi
apply_patch || { fail "git apply failed"; exit 1; }
info "Applied the Isambard 3 site patch to $SUITE_ID (r$SUITE_REV) in $SUITE_DIR."
